#
# Persistent Volumes Zoning Guide
# When deploying on a cloud that spans multiple availability zones, certain steps are required in order to use persistent volumes. These steps will vary depending on the version of Kubernetes being provided by your cloud.
#
# https://docs.couchbase.com/operator/1.2/persistent-volumes-zoning-guide.html
#
apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-server
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  authSecret: cb-auth-secret
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  cluster:
    dataServiceMemoryQuota: 6144
    indexServiceMemoryQuota: 2048
    searchServiceMemoryQuota: 512
    eventingServiceMemoryQuota: 512
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    # view these in the cb-server with a port forward:
    # kubectl port-forward cb-server-0000 8091:8091
    # open in a browser:
    # http://localhost:8091/ui/index.html#!/settings/autoFailover
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 10
    autoFailoverServerGroup: true
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 2048
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 3
      # changing the services list REQUIRES a delete/apply
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
